version: '3'

services:
    platform:
        build:
            context: ../../platform/docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        depends_on:
            - pgsql
            - redis
            - m_cf
            - ms_manager
        ports:
            - '${APP_PORT:-80}:80'
            - '${SECURITY_APP_PORT:-443}:443'
            - '${HMR_PORT:-8080}:8080'
        volumes:
            - '../../platform:/var/www/html'
        environment:
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD:-secret}'
            GRPC_MANAGER_HOST: ms_manager
            GRPC_MANAGER_PORT: 50041
            GRPC_CF_HOST: m_cf
            GRPC_CF_PORT: 50051
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - embers

    pgsql:
        image: postgres:14
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        networks:
            - embers
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}"
                ]
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - embers
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    ms_manager:
        image: ghcr.io/emb3rs-project/ms-grpc-manager:dev
        depends_on:
            - m_cf
            - m_gis
            - m_teo
            - m_mm
            - m_bm
        links:
            - m_cf
            - m_gis
            - m_teo
            - m_mm
            - m_bm
        ports:
            - '50041:50041'
        environment:
            GRPC_VERBOSITY: DEBUG
            GRPC_TRACE: http
            GRPC_HOST: 0.0.0.0
            GRPC_PORT: 50041
            CF_HOST: m_cf
            CF_PORT: 50051
            GIS_HOST: m_gis
            GIS_PORT: 50052
            TEO_HOST: m_teo
            TEO_PORT: 50053
            MM_HOST: m_mm
            MM_PORT: 50054
            BM_HOST: m_bm
            BM_PORT: 50055
            DATABASE_URL: 'postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD:-secret}@${DB_CONNECTION:-pgsql}:${DB_PORT:-5432}/${DB_DATABASE}'
            GIS_TEO_ITERATION_MODE: 'True'
        command: "export PYTHONPATH=ms_grpc/plibs:module"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - embers

    m_cf:
        image: ghcr.io/emb3rs-project/m-grpc-core-functionalities:dev
        ports:
            - '50051:50051'
        environment:
            GRPC_VERBOSITY: DEBUG
            GRPC_TRACE: http
            GRPC_HOST: 0.0.0.0
            GRPC_PORT: 50051
        command: "export PYTHONPATH=ms_grpc/plibs:module"
        networks:
            - embers

    m_gis:
        image: ghcr.io/emb3rs-project/m-grpc-gis:dev
        ports:
            - '50052:50052'
        volumes:
            - './gurobi.lic:/app/gurobi.lic'
        environment:
            GRPC_VERBOSITY: DEBUG
            GRPC_TRACE: http
            GRPC_HOST: 0.0.0.0
            GRPC_PORT: 50052
            GRB_LICENSE_FILE: gurobi.lic
        command: "export PYTHONPATH=ms-grpc/plibs:module"
        networks:
            - embers

    m_teo:
        image: ghcr.io/emb3rs-project/m-grpc-teo:dev
        ports:
            - '50053:50053'
        volumes:
            - './gurobi.lic:/app/gurobi.lic'
        environment:
            GRPC_VERBOSITY: DEBUG
            GRPC_TRACE: http
            GRPC_HOST: 0.0.0.0
            GRPC_PORT: 50053
            GRB_LICENSE_FILE: gurobi.lic
        command: "export PYTHONPATH=ms-grpc/plibs:module"
        networks:
            - embers

    m_mm:
        image: ghcr.io/emb3rs-project/m-grpc-market:dev
        ports:
            - '50054:50054'
        volumes:
            - './gurobi.lic:/app/gurobi.lic'
        environment:
            GRPC_VERBOSITY: DEBUG
            GRPC_TRACE: http
            GRPC_HOST: 0.0.0.0
            GRPC_PORT: 50054
            GRB_LICENSE_FILE: gurobi.lic
        command: "export PYTHONPATH=ms-grpc/plibs:module"
        networks:
            - embers

    m_bm:
        image: ghcr.io/emb3rs-project/m-grpc-business:dev
        ports:
            - '50055:50055'
        environment:
            GRPC_VERBOSITY: DEBUG
            GRPC_TRACE: http
            GRPC_HOST: 0.0.0.0
            GRPC_PORT: 50055
        command: "export PYTHONPATH=ms-grpc/plibs:module"
        networks:
            - embers

networks:
    embers:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local